using System;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Dalamud.Plugin.Services;

namespace VenueRaffle.Services;

/// <summary>
/// Validates offline install-bound licenses.
///
/// The plugin stores only a random local Install ID and a signed license token.
/// It does not call a server and does not use character names, account data, or hardware identifiers.
/// </summary>
public sealed class OfflineLicenseService
{
    private const string PluginName = "VenueRaffle";

    // Public key for verifying licenses generated by the developer-only license script.
    // Keep the matching private key outside the plugin DLL and never distribute it to users.
    private const string PublicKeySubjectPublicKeyInfoBase64 =
        "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFQP38rjVc2qMH3ple/gBbYOY5yLPnZBxF3n1DDOGJLy4MvywJVyxl1YieS2J4AczavvkQRHMkH/82kNX2QVJJw==";

    private readonly Configuration configuration;
    private readonly IPluginLog log;

    public OfflineLicenseService(Configuration configuration, IPluginLog log)
    {
        this.configuration = configuration;
        this.log = log;

        if (string.IsNullOrWhiteSpace(this.configuration.InstallId))
        {
            this.configuration.InstallId = Guid.NewGuid().ToString("N");
            this.configuration.Save();
        }
    }

    public LicenseStatus CurrentStatus => this.ValidateToken(this.configuration.LicenseToken);

    public bool IsLicensed => this.CurrentStatus.IsValid;

    public LicenseStatus ImportLicenseText(string? licenseText)
    {
        var status = this.ValidateToken(licenseText);

        if (!status.IsValid)
            return status;

        this.configuration.LicenseToken = licenseText?.Trim() ?? string.Empty;
        this.configuration.Save();
        return this.CurrentStatus;
    }

    public void ClearLicense()
    {
        this.configuration.LicenseToken = string.Empty;
        this.configuration.Save();
    }

    public LicenseStatus ValidateToken(string? tokenOrJson)
    {
        if (string.IsNullOrWhiteSpace(tokenOrJson))
            return LicenseStatus.Invalid("No license installed.");

        try
        {
            var json = DecodeLicenseText(tokenOrJson.Trim());
            var payload = JsonSerializer.Deserialize<LicensePayload>(json, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            });

            if (payload is null)
                return LicenseStatus.Invalid("License text is empty or invalid.");

            if (!string.Equals(payload.Plugin, PluginName, StringComparison.Ordinal))
                return LicenseStatus.Invalid("This license is not for VenueRaffle.");

            if (!string.Equals(payload.InstallId, this.configuration.InstallId, StringComparison.OrdinalIgnoreCase))
                return LicenseStatus.Invalid("This license belongs to a different install ID.");

            if (string.IsNullOrWhiteSpace(payload.Signature))
                return LicenseStatus.Invalid("License signature is missing.");

            if (!VerifySignature(payload))
                return LicenseStatus.Invalid("License signature is invalid.");

            if (!string.IsNullOrWhiteSpace(payload.ExpiresAtUtc) &&
                DateTimeOffset.TryParse(payload.ExpiresAtUtc, out var expiresAt) &&
                expiresAt < DateTimeOffset.UtcNow)
            {
                return LicenseStatus.Invalid($"License expired on {expiresAt:yyyy-MM-dd}.", payload);
            }

            return LicenseStatus.Valid(payload);
        }
        catch (Exception ex)
        {
            this.log.Warning(ex, "VenueRaffle license validation failed.");
            return LicenseStatus.Invalid($"License validation failed: {ex.Message}");
        }
    }

    private static string DecodeLicenseText(string text)
    {
        // Accept either raw JSON or a base64 token containing the JSON.
        if (text.StartsWith("{", StringComparison.Ordinal))
            return text;

        var compact = text.Replace("\r", string.Empty).Replace("\n", string.Empty).Trim();
        var bytes = Convert.FromBase64String(compact);
        return Encoding.UTF8.GetString(bytes);
    }

    private static bool VerifySignature(LicensePayload payload)
    {
        using var ecdsa = ECDsa.Create();
        ecdsa.ImportSubjectPublicKeyInfo(Convert.FromBase64String(PublicKeySubjectPublicKeyInfoBase64), out _);

        var data = Encoding.UTF8.GetBytes(BuildCanonicalPayload(payload));
        var signature = Convert.FromBase64String(payload.Signature ?? string.Empty);
        return ecdsa.VerifyData(data, signature, HashAlgorithmName.SHA256);
    }

    public static string BuildCanonicalPayload(LicensePayload payload)
    {
        return string.Join("|", new[]
        {
            payload.Plugin ?? string.Empty,
            payload.InstallId ?? string.Empty,
            payload.LicensedTo ?? string.Empty,
            payload.IssuedAtUtc ?? string.Empty,
            payload.ExpiresAtUtc ?? string.Empty,
        });
    }

    public sealed class LicensePayload
    {
        public string Plugin { get; set; } = PluginName;
        public string InstallId { get; set; } = string.Empty;
        public string LicensedTo { get; set; } = string.Empty;
        public string IssuedAtUtc { get; set; } = string.Empty;
        public string? ExpiresAtUtc { get; set; }
        public string? Signature { get; set; }
    }

    public sealed class LicenseStatus
    {
        private LicenseStatus(bool isValid, string message, LicensePayload? payload)
        {
            this.IsValid = isValid;
            this.Message = message;
            this.Payload = payload;
        }

        public bool IsValid { get; }
        public string Message { get; }
        public LicensePayload? Payload { get; }

        public static LicenseStatus Valid(LicensePayload payload)
        {
            var name = string.IsNullOrWhiteSpace(payload.LicensedTo) ? "this install" : payload.LicensedTo;
            return new LicenseStatus(true, $"Licensed to {name}.", payload);
        }

        public static LicenseStatus Invalid(string message, LicensePayload? payload = null)
            => new(false, message, payload);
    }
}
